# Generated by Django 3.1.12 on 2021-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(choices=[('-', '-'), ('self-employeed', 'self-employeed'), ('employeed', 'employeed')], default='-', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('Amount', models.IntegerField()),
                ('Income', models.CharField(max_length=255)),
                ('Expense', models.CharField(max_length=255)),
            ],
        ),
    ]
